# Generated by Django 4.0.4 on 2022-05-09 08:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(default='1967-06-01')),
                ('photo', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mark', models.IntegerField()),
                ('rating', models.FloatField()),
                ('type', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='')),
                ('date_of_public', models.DateField(default=datetime.date(2022, 5, 9))),
                ('address', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_forum.director')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date(2022, 5, 9))),
                ('likes_count', models.IntegerField()),
                ('dislikes_count', models.IntegerField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_forum.post')),
            ],
        ),
    ]
